[mypy]
python_version = 3.13
warn_unused_configs = True
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_defs = False
follow_imports = silent
show_error_codes = True

[mypy-uber.utils]
check_untyped_defs = True

[mypy-uber.config]
check_untyped_defs = True

[mypy-run_server]
check_untyped_defs = True
